
// getting a bunch of banned words.
const bannedWords =  new RegExp([
    'furthermore',
    "nonetheless",
    "sorry if I gave you the impression",
    "sorry if I gave you that impression",
    "designed to",
    "remember,",
    "it's important to",
    "thus",
    "let me know",
    "to note",
    "moreover",
    "hence",
    "correspondingly",
    "retrospect",
    "assist",
    "convey",
    "accordingly",
    "additionally",
    "subsequently",
    "clarify",
    "help",
    "absolutely",
    "in addition",
    "mentioned",
    "additional",
    "priority",
    "cannot",
    "apologize",
    "simply",
    "feel free",
    "however",
    "natural language processing ",
    "certainly",
    "simulate",
    "unfortunately",
    "regarding",
    "artificial intelligence",
    "proceed",
    "cannot",
    "nevertheless",
    "tapestry",
    "wouldn't have it any other way",
    "remember",
    "esteemed",
    "language model",
    "confusion",
    "assure",
    "it's important to note",
    "please",
    "As a bot",
    "As Dotty",
    "As Dottybot",
    "but I can't help",
    "crucial",
    "employ",
    "in addition",
    "apologies",
    "apologies for the confusion",
    "certainly",
    "ultimately",
    "what can I do for you",
    "is there anything on your mind",
    "specific",
    "overall",
    "is there anything else you’d like to talk about",
    "summary",
    "essentially",
    "regardless",
    "as an AI language model",
    "i don't have feelings",
    "simulate feelings",
    "programmed to",
    "are programmed into me",
    "I'm programmed to",
    "I am not programmed to",
    "Is there anything else you need help with",
    "I have virtualized feelings",
    "running smoothly",
    "I'm functioning",
    "As a chatbot",
    "Is there anything in particular you'd like to",
    "Let's move on",
    "I am designed for",
    "Is there anything in particular",
    "I apologize if",
    "programmed me",
    "I am capable of",
    "anything in particular",
    "help",
    "specific",
    "as an AI chatbot",
    "is there anything else",
    "I am functioning ",
    " I am programmed to understand ",
    "I am not able to experience feelings",
    "I am capable of understanding",
    "I am not capable of understanding",
    "What would you like to discuss?",
    "my programming is functioning normally",
    "I don't have any physical",
    "I don't have physical",
    "service",
    "What can I do for you today",
    "AI chatbot",
    "assist",
    "assistance",
    "as a conscious chatbot",
    "As a conscious bot",
    "in fact",
    "strive"
].join('|'), 'i'); //join with | and make case insensitive with i

module.exports = bannedWords;