module.exports = {
    name: 'kitty',
    description: 'Shows a kitty pic',
    async execute(interaction, client) {

 
        // first check if interaction and options exist
        if (interaction && interaction.options) {
            // get the options from the interaction
            const type = interaction.options.getString('type');
        

        // now u got the type of kitty they want, so u can do different stuff depending on the type
        if (type === 'manul') {
            // define a list of manul pics
            const pics = [
                "https://giphy.com/clips/SWAG-winter-cats-seasons-USGOwslFbI7czAxahZ",
                'https://i.makeagif.com/media/7-18-2014/QXVCFz.gif',
                'https://giphy.com/gifs/reaction-mrw-screen-Tq0pFzzBpg4SI',
                'https://tenor.com/view/manul-pallas-cat-rolling-cuddle-cuddle-roll-gif-26410302',
                'https://tenor.com/view/manul-pallas-cat-cute-gif-21607590',
                'https://tenor.com/view/manul-pallas-cat-sticker-cat-dm4uz3-gif-21083490',
                'https://i.pinimg.com/originals/e2/a6/04/e2a604a5615d890f60870ecfcea1db0d.gif',
                'https://i.pinimg.com/originals/7a/3f/1b/7a3f1b5b021106d1dcc40e205011b36c.gif',
                'https://i.gifer.com/BJah.gif',
                'https://i.makeagif.com/media/5-18-2023/qexKFn.gif',
                'https://gifer.com/en/BJat',
                'https://gifer.com/en/BJao',
                'https://media.tenor.com/images/40e3550fc57ad035277d94bb94bcaa3d/tenor.gif',
                'https://64.media.tumblr.com/f300cacd754e1eb4315a8ce9b7683314/tumblr_mmtj6dRV021resz13o1_250.gif',
                'https://66.media.tumblr.com/tumblr_m478k4fh701qisaxro1_250.gif',
                'https://thumbs.gfycat.com/WeirdTerrificIndianjackal-max-1mb.gif',
                'https://media.tenor.com/images/87446a1691d3bb78afeca8a73691a078/tenor.gif',
                'https://c.tenor.com/fglOwY1fGNsAAAAM/manul-pallas-cat.gif',
                'https://thumbs.gfycat.com/FoolhardyPlayfulKitty-size_restricted.gif',
                'https://i.pinimg.com/originals/70/42/3a/70423a7666969b330e123e37efcc8498.gif',
                'https://img1.picmix.com/output/pic/normal/8/2/0/1/5171028_3dec3.gif',
                'https://thumbs.gfycat.com/MilkyThoseBlackbuck-size_restricted.gif',
                'https://64.media.tumblr.com/1e207762df60d92f2e09502a979c2ba2/c34ab316327a8518-61/s640x960/914ab4f53c5f7bcf9693cd552def4b269eeb736b.gifv',
                'https://64.media.tumblr.com/e4865db5a72aa49969e58801dac94f2e/tumblr_n80rytWaEh1rx5st2o1_400.gif',
                'https://64.media.tumblr.com/7af0269b7e589a15de853d1af20ae124/b467aa66f807da83-66/s640x960/90441b443a39f669e428212e513e698dcb4b45d3.gifv',
                'https://64.media.tumblr.com/f46990023d4e3b872215e0ce21e4e3e1/b467aa66f807da83-dc/s640x960/4fcc10bf905b576727af693534979cb758cfffab.gifv',
                'https://media.tenor.com/HftjEmsB0pQAAAAM/manul-pallas-cat.gif',
                'https://64.media.tumblr.com/49a246badd411798b3f6ac4d7f39cbeb/cf709cf4b3abb001-46/s400x600/33e9b427c05b66a9886ac1dde44c11b2aac4f222.gifv',
                'https://64.media.tumblr.com/01110418df1c3c6e48e61282e9bfdea6/cf709cf4b3abb001-c6/s400x600/4376fcd2a6e6f69c6ad78a36733cb903c3d284ac.gifv',
                'https://tenor.com/view/pallas-cat-cat-cute-cat-cute-pallas-cat-dirk-gif-24844897',
                'https://tenor.com/view/manul-pallas-cat-manul-cat-gif-26136860',
                'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/465d0c33-a5aa-4d36-8e06-53dcee114fd5/d93yr89-4dd19586-0776-4311-92ca-02ba88850e39.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwic3ViIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsImF1ZCI6WyJ1cm46c2VydmljZTpmaWxlLmRvd25sb2FkIl0sIm9iaiI6W1t7InBhdGgiOiIvZi80NjVkMGMzMy1hNWFhLTRkMzYtOGUwNi01M2RjZWUxMTRmZDUvZDkzeXI4OS00ZGQxOTU4Ni0wNzc2LTQzMTEtOTJjYS0wMmJhODg4NTBlMzkuZ2lmIn1dXX0.8mUgSTUNvm8W6lNuKge1ZhSolNi0P8gQoENm6ufYyU8',
                'https://tenor.com/view/pallas-pallas-cat-manul-cat-gif-20906933',
                'https://tenor.com/view/pallas-cat-what-huh-gif-14070902',
                'https://tenor.com/view/cat-gif-6071885',
                'https://tenor.com/view/manul-pallas-cat-rolling-cuddle-cuddle-roll-gif-26410302',
                'https://64.media.tumblr.com/a2504a1afdea347c2c66503ae63710c3/tumblr_mmtj6dRV021resz13o4_250.gif',
                'https://tenor.com/view/manul-pallas-cat-manul-cat-gif-26136867',
                'https://i255.photobucket.com/albums/hh145/xmrsdanifilth/Animals/Pallas%20Cats/Manul-Kittens1.gif',
                'https://tenor.com/view/manul-pallas-cat-manul-cat-gif-26136862',
                'https://tenor.com/view/manul-lazy-lazy-manul-sleep-gif-26516029',
                'https://tenor.com/view/manul-cat-generator-manul-generator-pallas-cat-gif-20710027',
                'https://tenor.com/view/cat-scritch-scratch-gif-23659187',
                'https://tenor.com/view/pallas-cat-manul-cat-pallas-gif-20906931',
                'https://tenor.com/view/cute-cat-cat-cute-manul-pallas-gif-21607843',
                'https://tenor.com/view/manul-pallas-cat-manuel-ruben-slikk-cute-gif-24948033',
                'https://tenor.com/view/manul-pallas-cat-kemo-curious-listen-gif-26411455',
                'https://tenor.com/view/cat-manul-snow-pallas-cat-turn-around-gif-24714377',
                'https://tenor.com/view/manul-pallas-cat-manul-cat-gif-26136861',
                'https://tenor.com/view/cat-hello-gif-25094727',
                'https://tenor.com/view/cat-pallas-manul-pallas-cat-gif-20906936',
                'https://tenor.com/view/cat-animal-paws-scratching-gif-15512593',
                'https://tenor.com/view/%D1%85%D0%BE%D0%BB%D0%BE%D0%B4%D0%BD%D0%BE-%D1%81%D0%BA%D1%83%D1%87%D0%BD%D0%BE-%D0%B1%D0%B0%D1%80%D1%81-%D1%81%D0%BE%D0%BD-gif-24711635',
                'https://tenor.com/view/pallas-cat-peekaboo-hi-meow-gif-14070981',
                'https://tenor.com/view/manul-gif-22066197',
                'https://tenor.com/view/goobis-manul-cat-suspicious-sus-gif-26515901',
                'https://tenor.com/view/elisttm-jotism-jotism_-jo-autism-jo_autism-gif-21343864',
                'https://tenor.com/view/bulgus-flopa-sogga-bobba-pallas-cat-gif-21365522',
                'https://tenor.com/view/brungus-floppa-manul-pallas-cat-humor-gif-26566218',
                'https://tenor.com/view/cat-cute-shy-pallas-cat-manul-cat-gif-26196386',
                'https://tenor.com/view/pallas-cat-pallas-manul-cat-manul-pallas-cat-winking-gif-19179991',
                'https://tenor.com/view/manul-pallas-cat-mungdaal-cute-bladee-gif-25498111',
                'https://tenor.com/view/brungus-anger-humor-manul-pallas-cat-gif-26566224',
                'https://tenor.com/view/wink-cat-snow-cute-cat-stare-gif-5283058',
                'https://tenor.com/view/manul-hi-cat-pallas-cat-gif-20652693',
                'https://tenor.com/view/elisttm-jotism-jotism_-jo-autism-jo_autism-gif-21343794',
                'https://tenor.com/view/manul-manul-morning-pallas-cat-good-morning-gm-gif-26228661',
                'https://tenor.com/view/manul-cute-cat-cute-cat-anger-gif-21607786',
                'https://tenor.com/view/manul-pallas-cat-licking-lips-emoji-cat-licking-lips-yum-gif-26114435',
                'https://tenor.com/view/elisttm-jotism-jotism_-jo-autism-jo_autism-gif-21343710',
                'https://tenor.com/view/manul-pallas-cat-lucki-real-rx-rx-papi-gif-26362070',
                'https://tenor.com/view/manul-gif-20905492',
                'https://tenor.com/view/manul-lazy-lazy-manul-sleep-gif-26516029',
                'https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNmhzeW03dmV6czM0Ymp5bmRjcjM2aWl4bnNxbzlsMzZkaWRoc3I1byZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/L4G60Ewtdoem4/giphy.gif',
                'https://giphy.com/gifs/cat-manul-haies-F0ZriKBdzZjnARVTeM'
            ];
            // choose a random manul pic
            const pic = pics[Math.floor(Math.random() * pics.length)];
            // send a response with the manul pic
            interaction.reply(pic);
        } 
        else if (type === 'cartoon') {
        // define a list of cartoon pics
        const pics = [
                "https://giphy.com/gifs/tutimon-shopping-spree-momo-cat-WyZ1D8gXF7QQsRkXw5",
                "https://giphy.com/gifs/AlphaESS-love-cat-sad-BGH9MWQegcu84hY9DT",
                "https://tenor.com/view/inazuma-eleven-go-galaxy-inago-galaxy-anime-cat-kitty-gif-23100661",
                "https://giphy.com/gifs/h44eLuIIYkfssTEwyb",
                "https://tenor.com/view/cat-wisdom-meow-gif-9267730",
                "https://tenor.com/view/saying-grace-jon-arbuckle-garfield-heres-you-food-amen-gif-19321143",
                "https://tenor.com/view/kibby-wizard-cat-slay-shay-merulus-twins-cat-gif-26456566",
                "https://tenor.com/view/homestuck-equius-cat-gif-7479752",
                "https://tenor.com/view/chococat-hello-kitty-litwik-gif-26324033",
                "https://tenor.com/view/little-black-black-black-cat-kitty-gif-16717318",
                "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/2c43bb6c-cca3-456a-be78-9b3f42220851/d4zolnj-86ee523e-e680-4eb2-87e3-55d10fe9706d.gif?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzJjNDNiYjZjLWNjYTMtNDU2YS1iZTc4LTliM2Y0MjIyMDg1MVwvZDR6b2xuai04NmVlNTIzZS1lNjgwLTRlYjItODdlMy01NWQxMGZlOTcwNmQuZ2lmIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.ld8qTixT6x7lngAEr6wE3Pue_xrWucs4xPL6QVeSptA",
                "https://giphy.com/gifs/cat-cute-fat-OqDXk7H0RfgGyyjtkL",
                "https://giphy.com/stickers/homestuck-3s4muLD3K6sN5iUn4u",
                "https://giphy.com/gifs/nehumanesociety-funny-cat-3o6fJbwYFe3SmVVQ4M",
                "https://tenor.com/view/love-mochi-gif-23257331",
                "https://tenor.com/view/black-cat-dance-gif-24807224",
                "https://giphy.com/gifs/hello-kitty-12WoP3M6zYupUs",
                "https://64.media.tumblr.com/tumblr_m8oroyA0cI1rdovqzo1_500.gif",
                "https://pa1.aminoapps.com/6366/e93ece89552a8c4a06d6e036518bf202ad205d25_00.gif",
                "https://giphy.com/gifs/hmm-listen-eye-on-you-gBEOMfhTJsPxko30hU",
                "https://giphy.com/gifs/cartoon-hello-kitty-sanrio-xT3i14Ddnbl75cEN4A",
                "https://giphy.com/gifs/hello-kitty-cute-kZqbBT64ECtjy",
                "https://giphy.com/gifs/cartoonnetwork-cartoon-network-blossom-powerpuff-girls-mdxsBbm66pJ1OUqz2O",
                "https://giphy.com/gifs/love-kitty-cartoons-Q72XkpZKhYV7W",
                "https://www.pinterest.cl/pin/lights-over-the-city--43487952638524748/",
                "https://tenor.com/view/cat-homestuck-mutini-vodka-mutini-vodka-gif-15244779",
                "https://giphy.com/gifs/cat-kitty-cute-DjYqNVITTewEM",
                "https://giphy.com/stickers/thinkbit-indie-game-filipino-brawl-quest-JmIXmkahyncDYPjIJf",
                "https://tenor.com/view/pusheen-cats-stormy-happy-smile-gif-14731085",
                "https://giphy.com/stickers/dressuptimeprincess-cats-kitty-timeprincess-EC2MjZ0EaNWtfai7dv",
                "https://tenor.com/view/homestuck-pusheen-furadia-gif-7292761",
                "https://tenor.com/view/kanaya-pu-sheen-homestuck-gif-8372794",
                "https://giphy.com/gifs/thesimpsons-l2JeiEBF9WWXCK5R6",
                "https://tenor.com/view/homestuck-pusheen-vriskers-gif-7292744",
                "https://giphy.com/clips/studiosoriginals-good-morning-i0zTwaJzcj2LxCmY5P",
                "https://giphy.com/gifs/drinking-apple-sip-epOu8XC1QMml4aX72D",
                "https://tenor.com/view/feferi-pu-sheen-homestuck-gif-8372838",
                "https://tenor.com/view/homestuck-pusheen-nepurrta-gif-7512844",
                "https://tenor.com/view/homestuck-pusheen-pawllux-gif-7292747",
                "https://giphy.com/gifs/HSeSi8IIywrF6",
                "https://tenor.com/view/eridan-pu-sheen-homestuck-gif-8372800",
                "https://giphy.com/gifs/drawing-painting-adom-woods-nE0kC9LQi3VsCdTLg1",
                "https://tenor.com/view/smile-cat-gif-26232996",
                "https://tenor.com/view/cat-cute-anime-flying-witch-chito-gif-17093994",
                "https://tenor.com/view/cat-eyes-creepy-white-witch-white-cat-gif-12508542",
                "https://giphy.com/gifs/cat-burythem-darkhimour-nkRRO6wsLxMqXxiKvZ",
                "https://giphy.com/gifs/gifnews-fox-adhd-14yBLTW0nH2V9K",
                "https://giphy.com/gifs/dominosuk-pizza-feelings-dominos-3osxYaxIZyzYcHPcnC",
                "https://giphy.com/gifs/gifnewstest-artists-on-tumblr-csaba-klement-Ls5DgFlS9xQ2I",
                "https://giphy.com/gifs/leomainecoon-chonk-chonksociety-society-tJOmxmTddfsLzuPOLD",
                "https://giphy.com/gifs/Carlsen-Kinderbuch-katze-meine-freundin-conni-kater-mau-d9jU6nQeiNDkvLYSku",
                "https://giphy.com/gifs/cat-cats-i-like-naps-WJ1fD3sUvJcIb8nfdE",
                "https://giphy.com/gifs/season-17-the-simpsons-17x4-3orieOsYilcxFU5MIw",
                "https://giphy.com/gifs/season-10-the-simpsons-10x20-3o6MbcDYW8cjAOJE1G",
                "https://giphy.com/gifs/fat-cat-14xmEqduE5QBMs",
                "https://giphy.com/gifs/kitty-cat-gif-cute-TF9OxDUKJVA6Q",
                "https://giphy.com/gifs/cartoon-kawaii-kitty-8VL96bR7PtBOE",
                "https://giphy.com/gifs/season-10-the-simpsons-10x16-3orieL8grL9jv04bU4",
                "https://giphy.com/gifs/season-16-the-simpsons-16x14-l2JebvLFYf9j3TmMM",
                "https://giphy.com/gifs/AlphaESS-wow-surprised-amazed-YyQk8mzP146ZdhlWKT",
                "https://giphy.com/gifs/ProBitExchange-hello-hi-greetings-38I3v6VURNa6QzHJTn",
                "https://giphy.com/gifs/cartoon-hello-kitty-sanrio-3o6wNIK2unphUcCcqQ",
                "https://tenor.com/view/inazuma-eleven-go-galaxy-inago-galaxy-anime-cat-stray-gif-23100651",
                "https://giphy.com/gifs/chubbiverse-ride-ufo-chubbicat-9IrTBo2LvyPa8utMK3",
                "https://giphy.com/gifs/cartoon-hello-kitty-sanrio-xT3i0UhQzqmZY0rIGY",
                "https://giphy.com/gifs/dance-ballet-cat-and-comics-T6eVqPRDurmRQraQjk",
        ];
        // choose a random cartoon pic
        const pic = pics[Math.floor(Math.random() * pics.length)];
        // send a response with the cartoon pic
        interaction.reply(pic);
        } 
        else if (type === 'wizard') { 
        // define a list of wizard kitty pics
        const pics = [
                "https://giphy.com/gifs/onrkL9U3V8Pbq",
                "https://tenor.com/view/kitten-cat-witch-hat-cute-gif-3524769",
                "https://tenor.com/view/pusheen-gif-22048214",
                "https://tenor.com/view/cat-witch-fire-flame-gif-7943522",
                "https://tenor.com/view/halloween-pusheen-cats-gif-18852962",
                "https://tenor.com/view/floating-magic-cat-greenscreen-gif-20012768",
                "https://tenor.com/view/google-take-look-gif-7283802",
                "https://tenor.com/view/googlecat-gif-7283795",
                "https://giphy.com/gifs/halloween-kristyglas-hyper-cats-r6kVlVyXJiKCvAMsMQ",
                "https://giphy.com/gifs/cat-night-forest-FB46EwMR6wNwwIF7cK",
                "https://tenor.com/view/wizard-cat-magus-cat-witch-cat-wicca-wiccan-gif-26941843",
                "https://tenor.com/view/wizard-magic-cat-spell-gif-5452899",
                "https://giphy.com/gifs/halloween-spooky-monster-kTS1UEAmyhkZF1yCxh",
                "https://giphy.com/gifs/MY-GIRLY-UNICORN-magic-cat-witch-xSFTogs2FBeyMN4Cvv",
                "https://giphy.com/gifs/hype-kristyglas-hyper-cat-CUzO75MCP8ZKsngyru",
                "https://giphy.com/gifs/witch-wizard-ta-da-809iM7dLeqCS0mcjvK",
                "https://giphy.com/gifs/cat-magic-wizard-IzTnxbkXnHp0Q3Flzj",
                "https://giphy.com/gifs/cat-magic-wizard-ZDs5f2iuI7SiAFVwhi",
                "https://giphy.com/gifs/nft-nfts-kristyglas-gm847x3P3bJFhmwhxT",
                "https://giphy.com/gifs/magic-natasha-maria-art-natashamariaart-Yz3eDwMjqAq4M8nnKk",
                "https://tenor.com/view/anjelle-magic-cat-witch-craft-floating-gif-17604654",
                "https://tenor.com/view/cats-grace-wizard-cat-irl-drawer-gif-18850176",
                "https://giphy.com/gifs/cat-halloween-cartoon-RVcMF53XeXmf78yYpP",
                "https://tenor.com/view/cute-kawaii-cartoon-whitaswhit-cat-gif-20500982",
                "https://tenor.com/view/cat-wizard-shocked-wtf-huh-gif-3644778",
                "https://tenor.com/view/halloween-kitty-witch-gif-12798035",
                "https://tenor.com/view/cat-witch-gif-20217934",
                "https://giphy.com/gifs/h-c-halowen-Z7skPQNucBB3kUDxeH",
                "https://tenor.com/view/cat-witch-potion-fantasy-gif-11296839",
                "https://tenor.com/view/harry-meower-cats-cat-flying-broom-wizard-cat-gif-15555690",
                "https://tenor.com/view/cats-cute-cat-cute-kitten-fluffy-kitten-kittens-gif-13060002",
                "https://tenor.com/view/black-cat-salem-sabrina-the-teenage-witch-gif-10710252",
                "https://tenor.com/view/magikaikai-magicat-magic-cat-magikai-gif-20378023",
                "https://tenor.com/view/wavy-cat-cat-wizard-cat-hello-summoning-gif-16564748",
                "https://tenor.com/view/nitw-witch-cat-halloween-gif-12031272",
        ];
        // choose a random wizard kitty pic
        const pic = pics[Math.floor(Math.random() * pics.length)];
        // send a response with the wizard kitty pic
        interaction.reply(pic);
        } 
        else if (type === 'spotty') {
        // define a list of spotted kitty pics
        const pics = [
            "https://giphy.com/gifs/2kP2hpWo0rog1h9zQo",
            "https://tenor.com/view/rusty-spotted-cat-cat-cute-cat-cute-worlds-smallest-cat-gif-19911750",
            "https://giphy.com/gifs/bbcearth-cat-cats-3o752ldHKQQtLcgCEo",
            "https://giphy.com/gifs/bbcearth-cat-cats-3o7521fCtDzodNtgIg",
            "https://giphy.com/gifs/bbcearth-cat-cats-3o7526wZgmsGwFMF3i",
            "https://tenor.com/view/cute-wyd-cat-wide-eyed-gif-13192431",
            "https://thumbs.gfycat.com/BossyDazzlingCockroach-size_restricted.gif",
            "https://64.media.tumblr.com/eff9bd8154ba6b8bdb1534734bd0ef21/tumblr_pejers6siI1qdhps7o3_r1_400.gif",
            "https://giphy.com/gifs/bbcearth-cat-cats-l0HUiYqriQZLSBBMQ",
            "https://i.pinimg.com/originals/bc/7a/fc/bc7afca0dadeac4e0ac95d790f5d016e.gif",
            "https://i.pinimg.com/originals/50/a6/19/50a619b1694eddd41da058534486cae4.gif",
            "https://i.pinimg.com/originals/e8/c4/e2/e8c4e2acaf8185d51d386772c70a9d61.gif",
            "https://tenor.com/view/wild-cat-rusty-spotted-cat-gif-23406790"
        ];
        // choose a random spotted kitty pic
        const pic = pics[Math.floor(Math.random() * pics.length)];
        // send a response with the spotted kitty pic
        interaction.reply(pic);
        } 
        else if (type === 'meow') {
        // randomize the response
        const options = [
                    'meow',
                    'nya!!',
                    'mewwww 🐾🐱',
                    'nyawn (^ω^)',
                    'ME-OW!',
                    "mewwwwmewwwwmewwwwmewwww",
                    "mewwwwmewwwwmewwwwmewwwwmewwwwmewwwwmewwwwmewwwwmewwwwmewwww",
                    "*purrs loudly",
                    "*purrs angrily",
                    'Rawwr! (coz cats think they’re savage)',
                    'Mroooooow',
                    'Meow meow meow!',
                    'Mroooooow',
                    'Purrr purr meownee!',
                    'Purrrpurr',
                    'mmmeoowww naps',
                    'hiss! 🐱',
                    'prrrp? 😸',
                    'mrowl! >:3',
                    '*licks paw*',
                    '*rolls over for belly rubs*',
                    '*stretches and yawns*',
                    '*knocks stuff off table*',
                    '*runs and zooms around*',
                    '*sharpens claws on couch*',
                    "'Scuse me hooman but I'ma need petss 🙀👉👈",
                    "Me-oww 😸 !",
                    "Mreow~!",
                    "Stop the regular daily BS. MORE PETS.",
                    "*Ripping up sofa because undying resentment*",
                    " Purrr ＾-＾ ~",
                    "Wait...I left that hairball where!? #oops",
                    "*purrs loudly in content ❤️😽❤️*"
                    ];
                try {
                    interaction.reply(options[Math.floor(Math.random() * options.length)]);
                    // Set the autoReply state to true
                    client.globalState.autoReply[interaction.channel.id] = true;
                } catch (error) {
                    console.error('Failed to reply to interaction:', error);
            }
        } else {
            // define a list of kitty pics
            const pics = [
                "https://tenor.com/view/defiant-earl-defiant-cat-gif-24550497",
                "https://tenor.com/view/cat-stand-no-nope-gif-6172951",
                "https://tenor.com/view/cat-kitty-gif-23521077",
                "https://tenor.com/view/cat-nice-day-gif-7174982",
                "https://tenor.com/view/cats-cute-cats-kittens-pussy-cats-kitty-cat-gif-21775883",
                "https://giphy.com/gifs/monty-cool-cat-happiness-jbKf1K7MhK5DErbeXY",
                "https://giphy.com/gifs/monty-cool-cat-happiness-BZhsdbxGaSAL8aAEHt",
                "https://tenor.com/view/byuntear-sad-sad-cat-cat-meme-gif-25617057",
                "https://tenor.com/view/cat-little-take-that-gif-13578329",
                "https://tenor.com/view/calculation-cat-gif-26041269",
                "https://giphy.com/gifs/i-believe-can-fly-cat-3o7btPitD723wPmVsk",
                "https://giphy.com/clips/studiosoriginals-kitten-sunshine-good-morning-love-l2jg3kT9ku7YeiuQrY",
                "https://giphy.com/gifs/community-bad-general-KHhs4BXpy5dba",
                "https://giphy.com/gifs/eating-gallery-watermelon-v0chtzArxVklO",
                "https://tenor.com/view/cats-feeding-gif-24196250",
                "https://tenor.com/view/kitty-cute-meow-cat-kitten-gif-16741198",
                "https://giphy.com/gifs/cat-eating-10eSPfhWNat2Xm",
                "https://giphy.com/gifs/MyPostcard-space-cat-cats-in-4w6SqkyIVvBqnNDgTs",
                "https://tenor.com/view/miau-cat-galaxy-sparkle-gif-5015834",
                "https://giphy.com/gifs/robert-downey-jr-cats-ASvQ3A2Q7blzq",
                "https://giphy.com/gifs/food-puppy-urlmYUSD7Bx6w",
                "https://tenor.com/view/jambo-jschlatt-whatever-huh-meme-jambo-schlatt-gif-25590760",
                "https://tenor.com/view/seriously-really-ernsthaft-cat-wirklich-gif-20763896",
                "https://giphy.com/gifs/stagewolf-cat-floof-lazy-PlUPmccLMq5v6J61wZ",
                "https://tenor.com/view/sad-cat-gif-26067066",
                "https://tenor.com/view/sad-cat-sunakook-tired-exhausted-gif-24687868",
                "https://tenor.com/view/cat-sad-gif-26415220",
                "https://tenor.com/view/cats-love-gif-24600012",
                "https://tenor.com/view/smilecat-gif-25781442",
                "https://tenor.com/view/cat-sleep-gif-23970142",
                "https://tenor.com/view/sleep-cat-two-cat-cat-cat-love-gif-23651667",
                "https://giphy.com/gifs/cat-kitty-kitten-kkEmNte4tRmZ0fgBhE",
                "https://giphy.com/gifs/cat-laugh-funny-q1MeAPDDMb43K",
                "https://giphy.com/gifs/hallmarkecards-cute-hallmark-shoebox-BzyTuYCmvSORqs1ABM",
                "https://giphy.com/stickers/S86b5qZE7fHWXOyy0P",
                "https://giphy.com/stickers/justin-transparent-iemwpbriqGa52BAAu1",
                "https://giphy.com/gifs/viralhog-viral-hog-bengal-kitten-wants-a-taste-of-sushi-KFaPIpOY3QPeudhfJw",
                "https://giphy.com/gifs/tiktok-aww-VdDeiUL5yOIyE3kdHA",
                "https://giphy.com/gifs/cat-6VoDJzfRjJNbG",
                "https://tenor.com/view/cat-melt-universe-cute-gif-17877220",
                "https://giphy.com/gifs/cat-baby-kawaii-FrEnONcaBGJ0c",
                "https://giphy.com/stickers/getsmittenkitten-nathan-the-catlady-nathanthecatlady-j921bcrmhN6C4dk7ne",
                "https://giphy.com/gifs/cat-gifs-gif-Df0JB6yixeNqg",
                "https://giphy.com/gifs/v6aOjy0Qo1fIA",
                "https://tenor.com/view/crazy-cat-dancing-crazy-cat-dance-moves-too-cool-i-got-this-gif-14504785",
                "https://giphy.com/gifs/justin-cat-stickers-PF83OmDFWCpP80l0X3",
                "https://giphy.com/gifs/editor-cat-gif-gifs-12T3GI5PpTrhoQ",
                "https://giphy.com/gifs/cat-sea-chicks-12PA1eI8FBqEBa",
                "https://giphy.com/gifs/editor-cat-gif-gifs-AImgH8tbFOZhe",
                "https://media.tenor.com/_D5SZLHde-AAAAAM/cat-bed-hair.gif",
                "https://giphy.com/gifs/justviralnet-cute-cat-animal-Jrk36uGtaZWOaBuHIX",
                "https://giphy.com/gifs/cats-cat-gif-cute-VJIXbKPKcOnio",
                "https://giphy.com/gifs/editor-kitten-cat-gif-gifs-KBCyVZsZMdhSM",
                "https://giphy.com/gifs/cat-WYEWpk4lRPDq0",
                "https://giphy.com/gifs/x4d1IhbMrGWGFCBZ4l",
                "https://tenor.com/view/cat-cats-cats-of-internet-cats-of-the-internet-cute-cat-gif-17675301",
                "https://giphy.com/gifs/cat-angry-kitten-KQwZNdsEtMecg",
                "https://giphy.com/gifs/YmVNzDnboB0RQEpmLr",
                "https://giphy.com/gifs/reaction-mood-2x0VePimPaFJDpGZ7H",
                "https://giphy.com/gifs/C9x8gX02SnMIoAClXa",
                "https://giphy.com/gifs/jerseydemic-3oriO0OEd9QIDdllqo",
                "https://giphy.com/gifs/cat-funny-animation-aC45M5Q4D07Pq",
                "https://giphy.com/gifs/catvidfest-cat-star-wars-fighting-rbcXe6TI1LUpW",
                "https://tenor.com/view/cats-gif-26316295",
                "https://giphy.com/gifs/cats-light-sabers-Ov5NiLVXT8JEc",
                "https://tenor.com/view/cat-witch-potion-fantasy-gif-11296839",
                "https://giphy.com/gifs/cat-fight-attack-G6fmc0H5xpZDO",
                "https://tenor.com/view/shenmue-shenmue-game-cats-game-cats-game-cat-mimi-gif-26256082",
                "https://tenor.com/view/cat-chess-gif-8913342",
                "https://tenor.com/view/cat-kitty-cute-adorable-this-is-my-toy-gif-17654445",
                "https://giphy.com/gifs/cat-kitten-hiding-dxqOkrl29R8ac",
                "https://giphy.com/gifs/cats-gl8ymnpv4Sqha",
                "https://giphy.com/gifs/dance-animal-kitty-xcfz72KwMHZ7O",
                "https://giphy.com/gifs/viralhog-viral-hog-kitty-spots-trouble-in-mirror-gm06f2sy5t2nDXfFKP"
            ];
            // choose a random kitty pic
            const pic = pics[Math.floor(Math.random() * pics.length)];
            // send a response with the kitty pic
            interaction.reply(pic);
        }
    }},
};